/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package TUGASPRAKOOP2;

import TUGASPRAKOOP.*;



/**
 *
 * @author Fatur Riski
 */
public class GUIGUDANGOBAT extends javax.swing.JFrame {

    /**
     * Creates new form GUIGUDANGOBAT
     */
    public GUIGUDANGOBAT() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        namagudangobatpurepharmacymedikacentre = new javax.swing.JLabel();
        txtkodeobat = new javax.swing.JTextField();
        kodeobat = new javax.swing.JLabel();
        namaobat = new javax.swing.JLabel();
        txtnamaobat = new javax.swing.JTextField();
        jenisobat = new javax.swing.JLabel();
        txtjenisobat = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtjumlahstok = new javax.swing.JTextField();
        hargaproduksi = new javax.swing.JLabel();
        txthargaproduksi = new javax.swing.JTextField();
        hargajual = new javax.swing.JLabel();
        txthargajual = new javax.swing.JTextField();
        tanggalexp = new javax.swing.JLabel();
        txttanggalexp = new javax.swing.JTextField();
        btncetak = new javax.swing.JButton();
        btnclose = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        memoobat = new javax.swing.JTextArea();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        namagudangobatpurepharmacymedikacentre.setText("GUDANG OBAT-OBATAN PURE PHARMACY MEDIKA CENTRE");

        kodeobat.setText("Kode Obat : ");

        namaobat.setText("Nama Obat : ");

        jenisobat.setText("Jenis Obat :");

        jLabel5.setText("Jumlah Stok :");

        hargaproduksi.setText("Harga Produksi :");

        hargajual.setText("Harga Jual :");

        tanggalexp.setText("Tanggal Expired :");

        btncetak.setText("CETAK");
        btncetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncetakActionPerformed(evt);
            }
        });

        btnclose.setText("CLOSE");
        btnclose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncloseActionPerformed(evt);
            }
        });

        memoobat.setColumns(20);
        memoobat.setRows(5);
        jScrollPane1.setViewportView(memoobat);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(kodeobat)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtjumlahstok, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                                    .addComponent(txtjenisobat, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtnamaobat, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtkodeobat, javax.swing.GroupLayout.Alignment.LEADING))
                                .addComponent(namaobat)
                                .addComponent(jenisobat)
                                .addComponent(jLabel5))
                            .addGap(40, 40, 40)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txthargajual)
                                .addComponent(txttanggalexp)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(btncetak)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                                    .addComponent(btnclose))
                                .addComponent(txthargaproduksi)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(tanggalexp)
                                        .addComponent(hargajual)
                                        .addComponent(hargaproduksi))
                                    .addGap(0, 0, Short.MAX_VALUE))))
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jScrollPane1)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(namagudangobatpurepharmacymedikacentre)))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(namagudangobatpurepharmacymedikacentre)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kodeobat)
                    .addComponent(hargaproduksi))
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtkodeobat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txthargaproduksi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(namaobat)
                    .addComponent(hargajual))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtnamaobat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txthargajual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jenisobat)
                    .addComponent(tanggalexp))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtjenisobat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txttanggalexp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtjumlahstok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btncetak)
                            .addComponent(btnclose))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btncetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncetakActionPerformed
        // TODO add your handling code here:
        memoobat.setText("");
        
        String kodeObat = txtkodeobat.getText();
        String namaObat = txtnamaobat.getText();
        String datajenisobat = txtjenisobat.getText();
        String datajumlahstok = txtjumlahstok.getText();
        String datahargaproduksi = txthargaproduksi.getText();
        String datahargajual = txthargajual.getText();
        String datatanggalexpired = txttanggalexp.getText();
        ATP1 obt = new ATP1(kodeObat,namaObat,datajenisobat,datajumlahstok,datahargaproduksi,datahargajual,datatanggalexpired);
        
        memoobat.append("Gudang Obat-Obatan Pure Pharmacy Medika Centre\n\n");
        memoobat.append("");
        memoobat.append("Kode Obat           : "+ obt.kodeobat+"\n");
        memoobat.append("Nama Obat          : "+ obt.namaobat+"\n");
        memoobat.append("Jenis Obat           : "+ obt.jenisobat+"\n");
        memoobat.append("Jumlah Stok         : "+ obt.jumlahstok+"\n");
        memoobat.append("Harga Produksi   : "+ obt.hargaproduksi+ "\n");
        memoobat.append("Harga Jual           : "+ obt.hargajual+"\n");
        memoobat.append("Tanggal Expired  : "+ obt.tanggalexpired+"\n");
    }//GEN-LAST:event_btncetakActionPerformed

    private void btncloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncloseActionPerformed
        // TODO add your handling code here:
            dispose();
    }//GEN-LAST:event_btncloseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIGUDANGOBAT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIGUDANGOBAT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIGUDANGOBAT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIGUDANGOBAT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIGUDANGOBAT().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncetak;
    private javax.swing.JButton btnclose;
    private javax.swing.JLabel hargajual;
    private javax.swing.JLabel hargaproduksi;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jenisobat;
    private javax.swing.JLabel kodeobat;
    private javax.swing.JTextArea memoobat;
    private javax.swing.JLabel namagudangobatpurepharmacymedikacentre;
    private javax.swing.JLabel namaobat;
    private javax.swing.JLabel tanggalexp;
    private javax.swing.JTextField txthargajual;
    private javax.swing.JTextField txthargaproduksi;
    private javax.swing.JTextField txtjenisobat;
    private javax.swing.JTextField txtjumlahstok;
    private javax.swing.JTextField txtkodeobat;
    private javax.swing.JTextField txtnamaobat;
    private javax.swing.JTextField txttanggalexp;
    // End of variables declaration//GEN-END:variables
}
