/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package TUGASPRAKOOP4;


/**
 *
 * @author Fatur Riski
 */
public class GUIMUTASI extends javax.swing.JFrame {

    /**
     * Creates new form GUIMUTASI
     */
    public GUIMUTASI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Mutasi = new javax.swing.JLabel();
        kodeobat = new javax.swing.JLabel();
        tanggalmutasi = new javax.swing.JLabel();
        tipemutasi = new javax.swing.JLabel();
        jumlahmutasi = new javax.swing.JLabel();
        txtkodeobt = new javax.swing.JTextField();
        txttglmutasi = new javax.swing.JTextField();
        txtjmlmutasi = new javax.swing.JTextField();
        cmbtipemutasi = new javax.swing.JComboBox<>();
        btncetak = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        memoMutasi = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Mutasi.setText("MUTASI");

        kodeobat.setText("Kode Obat :");

        tanggalmutasi.setText("Tanggal Mutasi :");

        tipemutasi.setText("Tipe Mutasi :");

        jumlahmutasi.setText("Jumlah Mutasi :");

        cmbtipemutasi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Keluar", "Masuk" }));

        btncetak.setText("SIMPAN");
        btncetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncetakActionPerformed(evt);
            }
        });

        memoMutasi.setColumns(20);
        memoMutasi.setRows(5);
        jScrollPane1.setViewportView(memoMutasi);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(173, 173, 173)
                .addComponent(Mutasi)
                .addGap(23, 23, 23))
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(kodeobat)
                            .addComponent(tanggalmutasi)
                            .addComponent(tipemutasi)
                            .addComponent(jumlahmutasi))
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txttglmutasi, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtkodeobt, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtjmlmutasi, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cmbtipemutasi, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(32, 32, 32)
                                .addComponent(btncetak)))))
                .addGap(0, 37, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(Mutasi)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kodeobat)
                    .addComponent(txtkodeobt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tanggalmutasi)
                    .addComponent(txttglmutasi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tipemutasi)
                    .addComponent(cmbtipemutasi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jumlahmutasi)
                    .addComponent(txtjmlmutasi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btncetak))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btncetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncetakActionPerformed
        // TODO add your handling code here:
        ClassMutasi objMutasi = new ClassMutasi();{
        objMutasi.setKodeobat(txtkodeobt.getText());
        objMutasi.tglmutasi = txttglmutasi.getText();
        objMutasi.jumlahmutasi = txtjmlmutasi.getText();
        objMutasi.tipemutasi = cmbtipemutasi.getItemAt(cmbtipemutasi.getSelectedIndex());
        memoMutasi.setText("Kode Obat          : "+objMutasi.getKodeobat());
        memoMutasi.append("\nTanggal Mutasi  : "+objMutasi.tglmutasi);
        memoMutasi.append("\nTipe Mutasi        : "+objMutasi.tipemutasi);
        memoMutasi.append("\nJumlah Mutasi    : "+objMutasi.jumlahmutasi);
     
    }
    }//GEN-LAST:event_btncetakActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIMUTASI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIMUTASI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIMUTASI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIMUTASI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIMUTASI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Mutasi;
    private javax.swing.JButton btncetak;
    private javax.swing.JComboBox<String> cmbtipemutasi;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jumlahmutasi;
    private javax.swing.JLabel kodeobat;
    private javax.swing.JTextArea memoMutasi;
    private javax.swing.JLabel tanggalmutasi;
    private javax.swing.JLabel tipemutasi;
    private javax.swing.JTextField txtjmlmutasi;
    private javax.swing.JTextField txtkodeobt;
    private javax.swing.JTextField txttglmutasi;
    // End of variables declaration//GEN-END:variables
}
